foods = []
food_dedup = set()
with open('foodlist.txt', 'r') as rf: # generated by `py main.py > foodlist.txt` and then deleting the nutrition advice output
    for line in rf:
        food_dedup.add(line[7:].lower().strip())
        foods.append((line[7:].lower().strip(), int(line[:6])))

foods.sort()

print(len(foods))

# print(foods)

print('\n'.join(sorted(x for x in food_dedup)))

# print('total:', len(f))

